author:
  name: Jerin Sunny

url: https://jerinsunny.github.io

baseurl: /blogs


owner : Jerin Sunny
year: 2024
date: 10-04-2024


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"



plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site


