author:
  name: Jerin Sunny

url: https://jerinsunny.github.io/blogs

baseurl: /blogs
destination: ./_site
google_analytics: G-DW62RVHCXG


owner : Jerin Sunny
year: 2024
date: 16-04-2024






plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site


